### ISSUE TITLE
Conversión 

### ISSUE THREAD

**Issue by JacobHdez** [Suavesito-Olimpiada/Algorithm-Analysis#1]
Como conviertes los archivos con el pandoc prro?

**Comment by Suavesito-Olimpiada** [comment]
Bueno, el comando que uso actualmente es el siguiente
```
pandoc -s --citeproc <nombre del archivo>.md -o <nombre_del_pdf>.pdf
```

Peero para el archivo de la [Clase 5](https://github.com/Suavesito-Olimpiada/Algorithm-Analysis/blob/master/assets/class/Class_5.md) metí un poco de código de [dot](https://www.graphviz.org/doc/info/lang.html) para hacer diagramas. Para que se metieran los diagramas e el pdf necesitas un filtro, específicamente [pandoc-plot](https://github.com/LaurentRDC/pandoc-plot), así como graphviz. y un comando distinto. Pero para lo más sencillo, el comando de arriba debería de funcionar. (edit: typo)

**Comment by JacobHdez** [comment]
Que amable, buen hombre.
